---
- name: Enable intranet services
  hosts: servera
  become: yes

  tasks:

  - name: latest version of httpd and firewalld installed
    yum:
      name: 
        - httpd
        - firewalld
      state: latest

  - name: firewalld enabled and running
    service: 
      name: firewalld
      enabled: true
      state: started

  - name: firewalld permits http service
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes

  - name: httpd enabled and running
    service:
      name: httpd
      enabled: true
      state: started


  - name: test html page is installed
    copy: 
      content: "Welcome to the example.com intranet!\n"
      dest: /var/www/html/index.html

  - name: connect to intranet web server
    uri: 
      url: http://192.168.0.117
      status_code: 200
